# Generated by Django 5.2.13 on 2026-08-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_tin', models.CharField(db_index=True, max_length=50, unique=True)),
                ('pharmacy_name', models.CharField(blank=True, default='', max_length=255)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('banned', 'Banned'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20)),
                ('status_reason', models.TextField(blank=True, default='')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
