# Generated by Django 5.2.13 on 2026-08-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantaccount',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
