# Generated by Django 5.2.13 on 2026-08-10 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantaccount',
            name='billing_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantaccount',
            name='billing_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenantaccount',
            name='billing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantaccount',
            name='free_trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantaccount',
            name='is_illustration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantaccount',
            name='paid_quarters_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenantaccount',
            name='payment_channel',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tenantaccount',
            name='payment_transaction_ref',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='tenantaccount',
            name='quarterly_fee_etb',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='tenantaccount',
            name='setup_fee_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantaccount',
            name='setup_fee_etb',
            field=models.PositiveIntegerField(default=15000),
        ),
        migrations.AddField(
            model_name='tenantaccount',
            name='subscription_paid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantaccount',
            name='subscription_payment_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TenantPaymentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_tin', models.CharField(db_index=True, max_length=50)),
                ('payment_kind', models.CharField(choices=[('setup', 'Setup'), ('quarterly', 'Quarterly')], db_index=True, max_length=20)),
                ('amount_etb', models.PositiveIntegerField()),
                ('payment_channel', models.CharField(max_length=64)),
                ('transaction_ref', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('quarter_number', models.PositiveIntegerField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payment_submissions', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_payment_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['pharmacy_tin', 'payment_kind', 'status'], name='tenants_ten_pharmac_ad3129_idx')],
            },
        ),
    ]
